version: '3.8'

services:
  rag_service:
    build: ./rag_service
    container_name: rag_service
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - EMBEDDER_MODEL=${EMBEDDER_MODEL}
    ports:
      - "5060:5060"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 5060 --log-level info  # Явный запуск Uvicorn
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5060/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
