version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: rag_db
      POSTGRES_USER: rag_user
      POSTGRES_PASSWORD: rag_password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - rag_network

  data_service:
    build:
      context: ./data_service
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    environment:
      DATABASE_URL: postgresql://rag_user:rag_password@postgres:5432/rag_db
    depends_on:
      - postgres
    networks:
      - rag_network

  rag_service:
    build:
      context: ./rag_service
      dockerfile: Dockerfile
    ports:
      - "5060:5060"
    environment:
      DATABASE_URL: postgresql://rag_user:rag_password@postgres:5432/rag_db
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DATA_SERVICE_URL: http://data_service:5050
    depends_on:
      - postgres
      - data_service
    networks:
      - rag_network

volumes:
  postgres_data:

networks:
  rag_network:
    driver: bridge 